"""Interactive first-run setup for rlaif.

Asks which channels to configure (negative, positive, or both), prompts
for the matching credentials, writes ``config.toml`` with safe defaults
(``allow = false`` on every channel), runs ``rlaif doctor`` to probe the
device(s), offers to auto-install rlaif into one or more MCP client
configs (falling back to a paste-into snippet for clients without an
auto-install adapter), and prints the remaining first-run checklist.

Intentionally does NOT flip ``allow`` or fire any device — that stays a
deliberate operator action.
"""

from __future__ import annotations

import getpass
import json
import os
import stat
import sys

from rlaif.config import default_config_path
from rlaif.doctor import run as doctor_run
from rlaif.installer import SUPPORTED as INSTALL_SUPPORTED
from rlaif.installer import install as installer_install
from rlaif.snippet import CLIENTS
from rlaif.snippet import run as snippet_run

# Templates kept format-string-friendly: callers ``json.dumps()`` each
# value so embedded quotes / unicode round-trip safely into TOML strings.

_CONFIG_HEADER = (
    "# rlaif config — generated by `rlaif init`.\n"
    "# Secrets can be overridden via env. See README for the full list.\n\n"
)

_NEG_PISHOCK_BLOCK = """[negative]
kind  = "pishock"
label = {label}

[negative.pishock]
username  = {username}
api_key   = {api_key}
sharecode = {sharecode}

[negative.safety]
# Stays false until you've walked through the first-run checklist below.
allow                    = false
max_intensity            = 25
max_duration_s           = 2
warn_threshold_intensity = 15
bucket_capacity          = 3
refill_seconds           = 600
i_understand_and_consent = false

"""

_NEG_OPENSHOCK_BLOCK = """[negative]
kind  = "openshock"
label = {label}

[negative.openshock]
api_token  = {api_token}
shocker_id = {shocker_id}
{base_url_line}

[negative.safety]
allow                    = false
max_intensity            = 25
max_duration_s           = 2
warn_threshold_intensity = 15
bucket_capacity          = 3
refill_seconds           = 600
i_understand_and_consent = false

"""

_POS_INTIFACE_BLOCK = """[positive]
kind  = "intiface"
label = {label}

[positive.intiface]
ws_url       = {ws_url}
client_name  = "rlaif"
{device_line}

[positive.safety]
# Stays false until you've walked through the first-run checklist below.
allow           = false
max_intensity   = 70
max_duration_s  = 5
bucket_capacity = 5
refill_seconds  = 30

"""


def _prompt(label: str, *, default: str | None = None, secret: bool = False) -> str:
    suffix = f" [{default}]" if default is not None else ""
    reader = getpass.getpass if secret else input
    while True:
        try:
            val = reader(f"{label}{suffix}: ").strip()
        except EOFError:
            print("\naborted.", file=sys.stderr)
            raise SystemExit(130) from None
        if val:
            return val
        if default is not None:
            return default
        print("  required. try again.")


def _confirm(label: str, *, default: bool = False) -> bool:
    hint = "Y/n" if default else "y/N"
    try:
        val = input(f"{label} [{hint}]: ").strip().lower()
    except EOFError:
        return False
    if not val:
        return default
    return val in {"y", "yes"}


def _prompt_channels() -> tuple[bool, bool]:
    """Ask which channels to configure. Returns (do_negative, do_positive)."""
    print("which channels would you like to configure?")
    print("  [1] negative only (shock; PiShock or OpenShock)")
    print("  [2] positive only (vibration; Intiface / buttplug.io)")
    print("  [3] both")
    while True:
        try:
            val = input("pick [1]: ").strip().lower()
        except EOFError:
            return (True, False)
        if val in {"", "1", "negative", "neg", "n"}:
            return (True, False)
        if val in {"2", "positive", "pos", "p"}:
            return (False, True)
        if val in {"3", "both", "b"}:
            return (True, True)
        print("  invalid; please try again.")


def _prompt_negative_kind() -> str:
    print("negative channel: which backend?")
    print("  [1] pishock  (api at pishock.com)")
    print("  [2] openshock (api.openshock.app or self-hosted)")
    while True:
        try:
            val = input("pick [1]: ").strip().lower()
        except EOFError:
            return "pishock"
        if val in {"", "1", "pishock", "ps"}:
            return "pishock"
        if val in {"2", "openshock", "os"}:
            return "openshock"
        print("  invalid; please try again.")


def _prompt_clients() -> list[str]:
    """Multi-select prompt for MCP clients to set up.

    Accepts comma- or space-separated indices and/or names, plus ``a``/
    ``all`` for everything and ``s``/``skip``/empty for nothing. Order
    of the returned list mirrors the order the operator typed; duplicates
    are coalesced.
    """
    print("\ninstall rlaif into your MCP client(s) now?")
    print("  auto-install where supported; paste-into snippet otherwise.")
    print("  (creates a `.rlaif.bak` next to each config we mutate.)")
    for i, client in enumerate(CLIENTS, start=1):
        marker = "" if client in INSTALL_SUPPORTED else "  [paste-into]"
        print(f"  [{i}] {client}{marker}")
    print("  [a] all")
    print("  [s] skip")
    print("pick one or more (e.g. '1,3' or 'claude-code cursor'):")
    while True:
        try:
            val = input("pick: ").strip().lower()
        except EOFError:
            return []
        if val in {"", "s", "skip"}:
            return []
        if val in {"a", "all"}:
            return list(CLIENTS)
        tokens = [t for t in val.replace(",", " ").split() if t]
        chosen: list[str] = []
        bad: str | None = None
        for tok in tokens:
            name: str | None = None
            if tok in CLIENTS:
                name = tok
            elif tok.isdigit():
                idx = int(tok) - 1
                if 0 <= idx < len(CLIENTS):
                    name = CLIENTS[idx]
            if name is None:
                bad = tok
                break
            if name not in chosen:
                chosen.append(name)
        if bad is not None:
            print(f"  invalid token: {bad!r}; please try again.")
            continue
        if not chosen:
            print("  pick at least one, or 's' to skip.")
            continue
        return chosen


def _setup_clients(chosen: list[str]) -> None:
    """Auto-install where supported, fall back to snippet otherwise.

    Failures on a single client (parse errors, conflicting existing
    entries) print to stderr via the installer and are non-fatal — the
    wizard keeps going so a single bad config doesn't take out the rest.
    """
    for client in chosen:
        print()
        if client in INSTALL_SUPPORTED:
            installer_install(
                client, dev_path=None, dry_run=False, force=False
            )
        else:
            print(f"# auto-install not available for {client}; emitting snippet:")
            snippet_run(client=client, dev_path=None)


def _build_negative_block() -> str:
    kind = _prompt_negative_kind()
    label = _prompt("  device label", default="collar")
    if kind == "pishock":
        print("pishock credentials from https://pishock.com/#/account:")
        username = _prompt("  username")
        api_key = _prompt("  api_key", secret=True)
        sharecode = _prompt("  sharecode (per-device)")
        return _NEG_PISHOCK_BLOCK.format(
            label=json.dumps(label),
            username=json.dumps(username),
            api_key=json.dumps(api_key),
            sharecode=json.dumps(sharecode),
        )
    print(
        "openshock credentials from https://openshock.app/#/dashboard/tokens"
        " (or your self-hosted dashboard):"
    )
    api_token = _prompt("  api_token", secret=True)
    shocker_id = _prompt("  shocker_id (uuid for the specific shocker)")
    base_url = _prompt(
        "  base_url",
        default="https://api.openshock.app",
    )
    if base_url and base_url != "https://api.openshock.app":
        base_url_line = f"base_url   = {json.dumps(base_url)}"
    else:
        base_url_line = '# base_url = "https://api.openshock.app"'
    return _NEG_OPENSHOCK_BLOCK.format(
        label=json.dumps(label),
        api_token=json.dumps(api_token),
        shocker_id=json.dumps(shocker_id),
        base_url_line=base_url_line,
    )


def _build_positive_block() -> str:
    print("positive channel: intiface (buttplug.io) gateway.")
    print("  install Intiface Central from https://intiface.com/central/ and start it")
    print("  before running `rlaif live-smoke --channel positive` later.")
    label = _prompt("  device label", default="vibe")
    ws_url = _prompt(
        "  ws_url (intiface websocket)", default="ws://localhost:12345"
    )
    print("  device selection: by index (most users want 0) or by name.")
    by_name = _confirm("  pick device by name?", default=False)
    if by_name:
        device_name = _prompt("  device_name (e.g. 'Lovense Domi')")
        device_line = f"device_name  = {json.dumps(device_name)}"
    else:
        device_index_str = _prompt("  device_index", default="0")
        device_line = f"device_index = {int(device_index_str)}"
    return _POS_INTIFACE_BLOCK.format(
        label=json.dumps(label),
        ws_url=json.dumps(ws_url),
        device_line=device_line,
    )


def run() -> int:
    if not sys.stdin.isatty():
        print("rlaif init requires an interactive TTY.", file=sys.stderr)
        return 2

    print("rlaif setup wizard. ctrl-c to abort.\n")

    cfg_path = default_config_path()
    if cfg_path.exists():
        if not _confirm(f"{cfg_path} already exists. overwrite?"):
            print("aborted; existing config left untouched.")
            return 0

    do_negative, do_positive = _prompt_channels()
    blocks: list[str] = []
    if do_negative:
        blocks.append(_build_negative_block())
    if do_positive:
        blocks.append(_build_positive_block())

    cfg_path.parent.mkdir(parents=True, exist_ok=True)
    content = _CONFIG_HEADER + "".join(blocks)
    # Credentials are written to config.toml in cleartext by design. rlaif is a
    # single-user CLI tool; the threat model is "another user on this machine
    # reads my config", which is mitigated by the 0600 mode set immediately
    # after the write. This matches how every MCP client (Claude Desktop,
    # Cursor, opencode, ...) stores API keys, and the README documents env-var
    # overrides for operators who'd rather keep secrets out of the file. See
    # CodeQL alert py/clear-text-storage-sensitive-data, dismissed won't-fix.
    cfg_path.write_text(content, encoding="utf-8")
    os.chmod(cfg_path, stat.S_IRUSR | stat.S_IWUSR)
    print(f"\nwrote {cfg_path} (mode 0600).")

    print("\nrunning `rlaif doctor` against the new config...\n")
    rc = doctor_run()
    if rc == 3:
        return 3

    chosen = _prompt_clients()
    if chosen:
        _setup_clients(chosen)

    print("\n--- next steps ---\n")
    if do_negative:
        print("negative channel:")
        print("  1. with allow=false, ask your agent to call rlaif_info.")
        print("     verify negative.device.online is true, and that")
        print("     rlaif_negative(1, 1) is refused with a `negative.safety.allow` error.")
        print(f"  2. set [negative.safety] allow = true in {cfg_path},")
        print("     restart your MCP client.")
        print("     run `rlaif live-smoke --channel negative` to fire one real shock.")
        print("  3. fire 4 back-to-back rlaif_negative(1,1) calls; confirm the 4th")
        print("     returns rate_limited=true.")
        print()
    if do_positive:
        print("positive channel:")
        print("  1. start Intiface Central and pair your device.")
        print("  2. with allow=false, call rlaif_info; verify positive.device.online")
        print("     and rlaif_positive(1, 1) is refused with `positive.safety.allow`.")
        print(f"  3. set [positive.safety] allow = true in {cfg_path},")
        print("     restart your MCP client.")
        print("     run `rlaif live-smoke --channel positive` to fire one real vibration.")
        print()
    print("tip: `rlaif log --tail 20` prints the on-disk ops log any time.")
    print("     `rlaif log --stats` prints rolling histograms across both channels.")
    return 0
