"""Interactive first-run setup for rlaif.

Prompts for PiShock credentials, writes ``config.toml`` with safe defaults
(``allow_shock = false``), probes the device, and prints the remaining
first-run checklist. Intentionally does NOT flip ``allow_shock`` or fire the
device — that stays a deliberate operator action.
"""

from __future__ import annotations

import getpass
import json
import os
import stat
import sys
from typing import Any

import pishock  # pyright: ignore[reportMissingTypeStubs]

from rlaif.config import ConfigError, default_config_path, load
from rlaif.server import Device
from rlaif.snippet import CLIENTS


CONFIG_TEMPLATE = """# rlaif config — generated by `rlaif init`.
# Secrets can be overridden via env: RLAIF_USERNAME, RLAIF_API_KEY, RLAIF_SHARECODE.

[auth]
username  = {username}
api_key   = {api_key}
sharecode = {sharecode}

[device]
label = {label}

[safety]
# Stays false until you've walked through the first-run checklist below.
allow_shock              = false
max_intensity            = 25
max_duration_s           = 2
warn_threshold_intensity = 15
i_understand_and_consent = false

[rate_limit]
bucket_capacity = 3
refill_seconds  = 600
"""


def _prompt(label: str, *, default: str | None = None, secret: bool = False) -> str:
    suffix = f" [{default}]" if default is not None else ""
    reader = getpass.getpass if secret else input
    while True:
        try:
            val = reader(f"{label}{suffix}: ").strip()
        except EOFError:
            print("\naborted.", file=sys.stderr)
            raise SystemExit(130)
        if val:
            return val
        if default is not None:
            return default
        print("  required. try again.")


def _confirm(label: str, *, default: bool = False) -> bool:
    hint = "Y/n" if default else "y/N"
    try:
        val = input(f"{label} [{hint}]: ").strip().lower()
    except EOFError:
        return False
    if not val:
        return default
    return val in {"y", "yes"}


def run() -> int:
    if not sys.stdin.isatty():
        print("rlaif init requires an interactive TTY.", file=sys.stderr)
        return 2

    print("rlaif setup wizard. ctrl-c to abort.\n")

    cfg_path = default_config_path()
    if cfg_path.exists():
        if not _confirm(f"{cfg_path} already exists. overwrite?"):
            print("aborted; existing config left untouched.")
            return 0

    print("pishock credentials from https://pishock.com/#/account:")
    username = _prompt("  username")
    api_key = _prompt("  api_key", secret=True)
    sharecode = _prompt("  sharecode (per-device)")
    label = _prompt("  device label", default="device")

    cfg_path.parent.mkdir(parents=True, exist_ok=True)
    content = CONFIG_TEMPLATE.format(
        username=json.dumps(username),
        api_key=json.dumps(api_key),
        sharecode=json.dumps(sharecode),
        label=json.dumps(label),
    )
    cfg_path.write_text(content, encoding="utf-8")
    os.chmod(cfg_path, stat.S_IRUSR | stat.S_IWUSR)
    print(f"\nwrote {cfg_path}.")

    print("\nprobing device (read-only)...")
    try:
        cfg = load(cfg_path)
    except ConfigError as exc:
        print(f"  config invalid after write: {exc}", file=sys.stderr)
        return 3

    try:
        api = pishock.PiShockAPI(username=cfg.auth.username, api_key=cfg.auth.api_key)
        shocker = api.shocker(
            sharecode=cfg.auth.sharecode,
            log_name="rlaif-init",
            name=cfg.device.label,
        )
        device = Device(api=api, shocker=shocker, label=cfg.device.label)
    except Exception as exc:
        print(
            f"  could not build pishock client: {type(exc).__name__}: {exc}",
            file=sys.stderr,
        )
        return 3

    info: dict[str, Any] = device.info_block()
    print("  device:", json.dumps(info, indent=2))
    online = bool(info.get("online"))

    print("\n--- next steps ---\n")
    print("1. connect rlaif to your MCP client. pick one and paste the output:")
    for client in CLIENTS:
        print(f"     rlaif snippet {client}")
    print()
    print("2. with allow_shock=false, ask your agent to call rlaif_info.")
    print("   verify device.online is true, and that rlaif(intensity=1, duration_s=1)")
    print("   is refused with an `allow_shock` error.")
    print()
    print(f"3. set allow_shock = true in {cfg_path}, then restart your MCP client.")
    print("   run `rlaif live-smoke` to fire one real minimum-intensity shock.")
    print()
    print("4. from the agent, fire 4 back-to-back rlaif(1, 1) calls; confirm")
    print("   the 4th returns rate_limited=true.")

    if not online:
        print(
            "\nwarning: device.online is false. investigate on pishock.com before proceeding."
        )
    return 0
