"""Interactive first-run setup for rlaif.

Prompts for PiShock credentials, writes ``config.toml`` with safe defaults
(``allow_shock = false``), runs ``rlaif doctor`` to probe the device, offers
to emit an MCP client snippet, and prints the remaining first-run checklist.
Intentionally does NOT flip ``allow_shock`` or fire the device — that stays
a deliberate operator action.
"""

from __future__ import annotations

import getpass
import json
import os
import stat
import sys

from rlaif.config import default_config_path
from rlaif.doctor import run as doctor_run
from rlaif.snippet import CLIENTS
from rlaif.snippet import run as snippet_run

CONFIG_TEMPLATE = """# rlaif config — generated by `rlaif init`.
# Secrets can be overridden via env: RLAIF_USERNAME, RLAIF_API_KEY, RLAIF_SHARECODE.

[auth]
username  = {username}
api_key   = {api_key}
sharecode = {sharecode}

[device]
label = {label}

[safety]
# Stays false until you've walked through the first-run checklist below.
allow_shock              = false
max_intensity            = 25
max_duration_s           = 2
warn_threshold_intensity = 15
i_understand_and_consent = false

[rate_limit]
bucket_capacity = 3
refill_seconds  = 600
"""


def _prompt(label: str, *, default: str | None = None, secret: bool = False) -> str:
    suffix = f" [{default}]" if default is not None else ""
    reader = getpass.getpass if secret else input
    while True:
        try:
            val = reader(f"{label}{suffix}: ").strip()
        except EOFError:
            print("\naborted.", file=sys.stderr)
            raise SystemExit(130) from None
        if val:
            return val
        if default is not None:
            return default
        print("  required. try again.")


def _confirm(label: str, *, default: bool = False) -> bool:
    hint = "Y/n" if default else "y/N"
    try:
        val = input(f"{label} [{hint}]: ").strip().lower()
    except EOFError:
        return False
    if not val:
        return default
    return val in {"y", "yes"}


def _prompt_client() -> str | None:
    """Ask which MCP client to emit a snippet for. Return the name or None."""
    print("\nemit a snippet for your MCP client now?")
    for i, client in enumerate(CLIENTS, start=1):
        print(f"  [{i}] {client}")
    print("  [s] skip")
    while True:
        try:
            val = input("pick: ").strip().lower()
        except EOFError:
            return None
        if val in {"", "s", "skip"}:
            return None
        if val in CLIENTS:
            return val
        if val.isdigit():
            idx = int(val) - 1
            if 0 <= idx < len(CLIENTS):
                return CLIENTS[idx]
        print("  invalid; please try again.")


def run() -> int:
    if not sys.stdin.isatty():
        print("rlaif init requires an interactive TTY.", file=sys.stderr)
        return 2

    print("rlaif setup wizard. ctrl-c to abort.\n")

    cfg_path = default_config_path()
    if cfg_path.exists():
        if not _confirm(f"{cfg_path} already exists. overwrite?"):
            print("aborted; existing config left untouched.")
            return 0

    print("pishock credentials from https://pishock.com/#/account:")
    username = _prompt("  username")
    api_key = _prompt("  api_key", secret=True)
    sharecode = _prompt("  sharecode (per-device)")
    label = _prompt("  device label", default="device")

    cfg_path.parent.mkdir(parents=True, exist_ok=True)
    content = CONFIG_TEMPLATE.format(
        username=json.dumps(username),
        api_key=json.dumps(api_key),
        sharecode=json.dumps(sharecode),
        label=json.dumps(label),
    )
    cfg_path.write_text(content, encoding="utf-8")
    os.chmod(cfg_path, stat.S_IRUSR | stat.S_IWUSR)
    print(f"\nwrote {cfg_path} (mode 0600).")

    print("\nrunning `rlaif doctor` against the new config...\n")
    # doctor prints its own snapshot and issues list. exit code 1 means
    # issues were found (expected: allow_shock=false is flagged); exit
    # code 3 means the pishock client could not be built, which is fatal
    # for init.
    rc = doctor_run()
    if rc == 3:
        return 3

    chosen = _prompt_client()
    if chosen is not None:
        print()
        snippet_run(client=chosen, dev_path=None)

    print("\n--- next steps ---\n")
    print("1. with allow_shock=false, ask your agent to call rlaif_info.")
    print("   verify device.online is true, and that rlaif(intensity=1, duration_s=1)")
    print("   is refused with an `allow_shock` error.")
    print()
    print(f"2. set allow_shock = true in {cfg_path}, then restart your MCP client.")
    print("   run `rlaif live-smoke` to fire one real minimum-intensity shock.")
    print()
    print("3. from the agent, fire 4 back-to-back rlaif(1, 1) calls; confirm")
    print("   the 4th returns rate_limited=true.")
    print()
    print("tip: `rlaif log --tail 20` prints the on-disk ops log any time.")
    return 0
